version: "2"
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mate_counter
      - POSTGRES_USER=matecounter
      - POSTGRES_PASSWORD=matecounter
  phppgadmin:
    image: zhajor/docker-phppgadmin
    depends_on:
      - postgres
    links:
      - postgres
    ports:
        - "8080:80"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  mate_counter:
    image: nyno/mate_counter
    environment:
      - DJANGO_DATABASE_NAME=mate_counter
      - DJANGO_DATABASE_USER=matecounter
      - DJANGO_DATABASE_PASSWORD=matecounter
      - DJANGO_DATABASE_HOST=postgres
      - DJANGO_DATABASE_PORT=5432

    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: '/bin/sh -c "./wait-for-it.sh postgres:5432 -- ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"'
