# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='key',
            field=models.CharField(default='key', max_length=10, unique=True),
        ),
    ]
